# Generated by Django 3.2.16 on 2022-10-18 13:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('time_minutes', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('link', models.CharField(blank=True, max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('link', models.CharField(blank=True, max_length=255)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('tag1', models.CharField(blank=True, choices=[('Inspirational', 'Inspirational'), ('Political', 'Political'), ('Cynical', 'Cynical'), ('Dark', 'Dark'), ('Comical', 'Comical'), ('Literary', 'Literary')], max_length=50)),
                ('tag2', models.CharField(blank=True, choices=[('Inspirational', 'Inspirational'), ('Political', 'Political'), ('Cynical', 'Cynical'), ('Dark', 'Dark'), ('Comical', 'Comical'), ('Literary', 'Literary')], max_length=50)),
                ('tag3', models.CharField(blank=True, choices=[('Inspirational', 'Inspirational'), ('Political', 'Political'), ('Cynical', 'Cynical'), ('Dark', 'Dark'), ('Comical', 'Comical'), ('Literary', 'Literary')], max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
