# Generated by Django 3.2.16 on 2022-10-20 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20221019_1304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='tag3',
        ),
        migrations.AlterField(
            model_name='quote',
            name='tag2',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
