# Generated by Django 3.2.16 on 2022-10-31 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_recipe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='tag1',
            field=models.CharField(blank=True, choices=[('Inspirational', 'Inspirational'), ('Political', 'Political'), ('Cynical', 'Cynical'), ('Dark', 'Dark'), ('Comical', 'Comical'), ('Literary', 'Literary'), ('Friends', 'Friends'), ('Love', 'Love'), ('Wisdom', 'Wisdom'), ('Poetry', 'Poetry'), ('Health', 'Health'), ('Famous People', 'Famous People')], max_length=50),
        ),
    ]
